### ISSUE TITLE
support docker image & generate docker-compose.yml using config.json

### ISSUE THREAD

**Issue by GopherJ** [paritytech/polkadot-launch#118]

**Comment by GopherJ** [comment]
using binary is quite limited. Also the approach of child processes can be improved by docker-compose

**Comment by shawntabrizi** [comment]
@GopherJ what you are describing is quite the different application. The reason we want to use the binary here is so that we can quickly iterate on development. You can link this project into the build folder of your Substrate project, and constantly update and launch a node with the latest code changes.

Using docker for an alternative project seems like a solid idea, but not the intention of this tool.
