### ISSUE TITLE
Remove binaries

### ISSUE THREAD

**Issue by joelamouche** [paritytech/polkadot-launch#54]
@pepyakin : 'Also, keeping these binaries in the repo leads to real inconveniences, see #15'

- remove binaries
- add instructions to build binaries

### add-collator
In polkadot
`cargo build --release -p test-parachain-adder-collator --features=real-overseer`
then find the binary under target/release/adder-collator

### relaychain
`cargo build --release --features=real-overseer`
then find the binary under target/release/polkadot

### parachain
`cargo build --release -p rococo-collato`

**Comment by joelamouche** [comment]
@pepyakin can you explain how to build rococo-collator please

**Comment by pepyakin** [comment]
sure, `cargo build --release -p rococo-collator`

**Comment by shawntabrizi** [comment]
binaries make it easy to test the software on its own. The repo should not be used as some part of some git clone process. Instead you can install the package with NPM which does not include the binaries.

I do not like the idea of accepting a PR which removes the binaries

**Comment by pepyakin** [comment]
FWIW, this discussion started again, and my latest answer besides the one on #15 is here https://github.com/paritytech/polkadot-launch/issues/52#issuecomment-772635269

As you can see, it turned out that these binaries in #52 were (and still are) broken, which again supports my claim that it is cumbersome to maintain this way. To add on that, these binaries are also only for macOS and Linux users (which I feel may be a majority actually) would not benefit from it.

**Comment by bkchr** [comment]
I'm also for removing these binaries :D

**Comment by shawntabrizi** [comment]
okay, yall can do what you think is best

**Comment by shawntabrizi** [comment]
```
# polkadot
cargo build --release --features=real-overseer

# cumulus
cargo build --release -p rococo-collator
``` 

how to build binaries needed for this to work
